### ISSUE TITLE
小白一个，看了一个下午都没有解决问题，求大佬解答一下

### ISSUE THREAD

**Issue by 0BrightStar0** [Aues6uen11Z/HonkaiHelper#11]
下面是AirtestIDE控制台的内容：
Info: filter not set, use raven.filter.FullPassFilter instead.
loading config from : C:\Users\star\AppData\Local\AirtestIDE\AirtestIDE\user.json
try loading plugin: firebase_plugin
plugin loaded: firebase_plugin
try loading plugin: headspin_plugin
plugin loaded: headspin_plugin
try loading plugin: selenium_plugin
plugin loaded: selenium_plugin
Traceback (most recent call last):
  File "jedi\evaluate\compiled\subprocess\__init__.py", line 248, in _send
    is_exception, traceback, result = pickle_load(self._process.stdout)
  File "jedi\_compatibility.py", line 464, in pickle_load
    return pickle.load(file, encoding='bytes')
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jedi\api\environment.py", line 74, in _get_subprocess
    info = self._subprocess._send(None, _get_info)
  File "jedi\evaluate\compiled\subprocess\__init__.py", line 260, in _send
    stderr,
jedi.api.exceptions.InternalError: The subprocess D:\diandong\Python\python.exe has crashed (EOFError('Ran out of input',), stderr=<empty/not available (ValueError('read of closed file',))>).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\plugins\editor\plugin.py", line 234, in init_jedi_env
  File "jedi\api\environment.py", line 302, in create_environment
    return Environment(path)
  File "jedi\api\environment.py", line 66, in __init__
    self._get_subprocess()
  File "jedi\api\environment.py", line 79, in _get_subprocess
    exc))
jedi.api.environment.InvalidPythonEnvironment: Could not get version information for 'D:\\diandong\\Python\\python.exe': InternalError("The subprocess D:\\diandong\\Python\\python.exe has crashed (EOFError('Ran out of input',), stderr=<empty/not available (ValueError('read of closed file',))>).",)

[20:13:16][DEBUG]<airtest.core.android.adb> D:\diandong\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe devices

 以下是在AirtestIDE运行时报错的内容：
from airtest.cli.parser import cli_setup（错误一）
from airtest.report.report import simple_report
from event import *（错误二）

**Comment by Aues6uen11Z** [comment]
我也菜鸡，单看这些也不太懂怎么解决。这个版本我也好久不用了，最近在写一个新版本，有挺大改动，到时候应该会出个比较详细的教程，可以期待下。

**Comment by 0BrightStar0** [comment]
太好了，那就有劳大佬了，非常期待
