### ISSUE TITLE
一直报错

### ISSUE THREAD

**Issue by wewieai** [Aues6uen11Z/HonkaiHelper#8]
[Start running..]
[2308] Failed to execute script AirtestIDE
Traceback (most recent call last):
  File "AirtestIDE.py", line 82, in <module>
  File "AirtestIDE.py", line 58, in main
  File "app\widgets\code_runner\tracer.py", line 72, in run_pyfile
  File "C:\Users\weiwei\Desktop\HonkaiHelper-1f8218c7907c34696ad98697e85b323e22b58c07\main.py", line 8, in <module>
    from event import *
ModuleNotFoundError: No module named 'event'
[Finished]

**Comment by Aues6uen11Z** [comment]
可以先看下#2
